### ISSUE TITLE
Excessive screen redrawing makes the program annoying / difficult to use with refreshable braille displays

### ISSUE THREAD

**Issue by youtux** [JFreegman/toxic#194] opened 2014-07-22 13:41 UTC
The ncurses interface continously refreshes, and the cursor goes continously around. This is at least the perception with my braille display (I am using it with BRLTTY 5.1 for the record).
So the software is hardly usable, since by default the display braille follows the movements of the cursor, and even disabling this functionality, I find it very annoying.
I don't have this problem with other programs like nano, irssi, ncmpc and other ncurses-based tools. Even with finch (that uses lignt of course), i have no problems.
Could this be fixed? Or is this something that has to do with the design of some libraries / the program / something else in general, even not regarding design?
Thank you.
Some infos that might help:
- I generated a new ID today
- I compile tox and toxic from git as the current snapshot (Tue Jul 22 14:26:15) in 2014 as a reference
- no audio support present (I am not installing openal, otherwise toxic won't
  compile here)
- my current distribution is Archlinux

the problem seems not present when not connected to the network - still, some flickering in the help screen makes the screen unconfortable to read.

Thank you very much for the attention.

My setup seems also affected by https://github.com/Tox/toxic/issues/96
so I currently am not able to get connected with this computer. I might switch to another but I would like to avoid this due to some reasons.
Hoping it's appropriate to report it here, my tox id is:
7C593F402A3C8632D87AB4B948D492294C39A6A614464ECF843CA3429FB023284180472C7475
I will try to connect when I'll be able to re-join the network from here with toxic, to be precise.
Thank you.

**Comment by gima** [comment] 2015-02-23 12:46
Here are screen recordings of the excessive redrawing. People...

[Don't blink](https://cloud.githubusercontent.com/assets/1252061/6327859/ae721bfe-bb69-11e4-9b59-8f0ade5a0ba1.gif)
[Please, don't blink](https://cloud.githubusercontent.com/assets/1252061/6327862/b1666856-bb69-11e4-93f4-e6a4615adb10.gif)

Bottom line: [Cannot *deal with it*](https://blog.codinghorror.com/the-works-on-my-machine-certification-program/). Come on guys, a seven months old bug?

**Comment by JFreegman** [comment] 2015-02-23 20:37
@gima this is evidently not a very common bug, and I think that it would require a great deal of my free time to fix, which is something that I don't have much of lately.

**Comment by louipc** [comment] 2015-02-23 21:25
@gima Why don't you send a patch? Thanks.

**Comment by mannol** [comment] 2015-02-23 21:39
@louipc now, now, we don't want to start the "fix it yourself" trend, it would give us a bad name. However, @gima as @JFreegman said, this bug is rather uncommon and to fix it would require us to switch focus from more important things like toxcore. We ask for your patience.

Thank you.

**Comment by louipc** [comment] 2015-02-24 01:36
On Mon 23 Feb 2015 13:39 -0800, mannol wrote:
> @louipc now, now, we don't want to start the "fix it yourself" trend, it
> would give us a bad name. However, @gima as @JFreegman said, this bug is
> rather uncommon and to fix it would require us to switch focus from more
> important things like toxcore. We ask for your patience.

People need to realize that in a small open source, free software project,
we're all working on this on our free time and we all have different
priorities.

It's reasonable to ask for people to actually contribute to see their needs
realised. If they have problems they can ask for help, but linking to some
"Works on My Machine Certification Program" blog post mocking developers
because they can't reproduce your bug doesn't help get it fixed.

No we don't want to start the "closed, won't fix trend" but if people are
disrespecting the contributors that might start to happen. So let's nip it in
the bud.

**Comment by henriqueleng** [comment] 2015-03-16 19:25
I'm with this problem too, I will look for a solution

**Comment by mrkiko** [comment] 2016-11-08 15:07
Seems fixed now. The cursor rarely flickers around, if at all. So I am closing this issue.
Thank to the guy who helped me reporting it.
I am grateful to you; and to all of you.

**Comment by mrkiko** [comment] 2016-11-08 15:08
Sorry, can not close. :D

**Closed** 2016-11-08 17:34 UTC
